### ISSUE TITLE
We should create more room stubs

### ISSUE THREAD

**Issue by jwgmeligmeyling** [MoodCat/MoodCat.me#105]
Als je nu bij Happy de tiende aanklikt, zou dat prima de eerste room van sad kunnen izjn
maar in de beleving dat het een relatief happy room is vote je sad muziek down
waardoor alle rooms naar de zelfde song exclusions toegaan

**Comment by jwgmeligmeyling** [comment]
I think this is important for the demo

**Comment by Jaapp-** [comment]
I've added 20 more rooms. I'm not sure what amount would  be ideal.

**Comment by eanker** [comment]
A lot of room names are now duplicate, we even have a triple.
Furthermore, can we limit it on 5/10. Because people can still scroll down and pick the last one.

**Comment by jwgmeligmeyling** [comment]
Because there are five rooms listed per mood, we should at least have 5 rooms per mood. This means 50 rooms.

**Comment by jwgmeligmeyling** [comment]
20 rooms should be enough for the demo btw, but seems the discussion about this is not over yet
