### ISSUE TITLE
Spell check the report

### ISSUE THREAD

**Issue by jwgmeligmeyling** [MoodCat/MoodCat.me#111]

**Comment by eanker** [comment]
I have been to all chapters and looked for errors from the spelling checker.
We now have only reds under words like Lombok and frontend,chatroom etc.
When looking for examples I saw we use soundcloud and SoundCloud, so we might make that more consistent.

**Comment by jwgmeligmeyling** [comment]
Ok perfect!

**Comment by jwgmeligmeyling** [comment]
(We might want to leave the issue open though, for one last check before delivery)

**Comment by eanker** [comment]
Yeah sure, I only looked at the texmaker spelling checker, though.

**Comment by TimvdLippe** [comment]
@JWGemligMeyling will send the report to some spellcheckers this evening, so the final version can be delivered on time with spellchecking.
