### ISSUE TITLE
UI doesn't update time of a song played in the rating game.

### ISSUE THREAD

**Issue by NickTUD** [MoodCat/MoodCat.me#117]
Whenever you play the rating game and pick a song, the time at the top of the screen doesn't update. It does when you press the rating game button again, but doesn't update it continuously after that.

Reproduction rate: 10/10

[Crappy gif](http://i.imgur.com/LE1dv6c.gif)

**Comment by jwgmeligmeyling** [comment]
Duplicate of https://github.com/MoodCat/MoodCat.me-Frontend/issues/114
