### ISSUE TITLE
Spamming == higher score?

### ISSUE THREAD

**Issue by maartentbm** [MoodCat/MoodCat.me#119]
The impression is given that users who click as often as possible on a thumbs up/down are getting high(er) on the leaderboard. I think this makes the votes less valuable, as spammers probably don't even listen to the music open in all of their 100 tabs. There must be a solution for this, right?

**Comment by TimvdLippe** [comment]
Yes we have implemented a fix to at least reduce the amount of spam at https://github.com/MoodCat/MoodCat.me-Core/pull/173
We could implement more filtering, by checking how many rooms a user is in, but this is of course a lower priority.

**Comment by TimvdLippe** [comment]
https://github.com/MoodCat/MoodCat.me-Core/issues/177 is the issue that describes the filtering. Closing this issue, as I think this is the only viable and simple solution.

**Comment by jwgmeligmeyling** [comment]
Fixed.
