### ISSUE TITLE
Design homepage

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#12]
Design the homepage with a category list of moods.

If the user is not logged in, he must redirected to a user login page.

Must be finished in order to start #5 .

**Comment by MoodCat** [comment]
I added a [small start](https://github.com/MoodCat/MoodCat.me-Frontend/pull/2) of a markup for the nav bar in a dark theme. 

IMO the dark background with light text goes very well with bright colors to be used in animations/images, and creates a slick, professional look. 

For inspiration, see the [Spotify webplayer](https://play.spotify.com/browse) or [plug.dj](http://plug.dj)
