### ISSUE TITLE
Decide what to do with chat messages

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#125]
The chat messages loaded when loading a room is confusing to users.
Some want to have timestamps in order to see who talked, however how useful would that be for existing discussions?

Therefore we can also decide to not load past chatmessages any more, but this requires timestamp selection instead of chatmessageid.

Both choices have yays and nays, but we should make a decision soon in order to prepare the backend and solve the confusion of users.

**Comment by jwgmeligmeyling** [comment]
We should bring the timestamps back, and show a list / count of active users imo.
