### ISSUE TITLE
Analyze usage of EEMCS data

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#17]
Figure out which parts of the provided data are usable to be able to extract Arousal and Valence for data storage.

**Comment by eanker** [comment]
After doing researching on the av-graph I found that we could use the following musical features: pitch,tempo,timbre,loudness and for arousal harmony,mode,tonality. 

For these musical features we can use the following low-level features:
pitch --> none (pitch salience is only if it pitched and not how high/low)
tempo --> bpm
timbre --> none (study on itself)
loudness --> loudness

harmony --> dissonance
mode --> key
tonality --> tonal (maybe)

**Comment by eanker** [comment]
How to go from tonality to tonal is not that clear.
I can't seem to figure it out.
Maybe it's not possible,but that problem needs to be found.

I thought there were a few where the tonal section missed.
If that's the case we can see if a song is tonal or not.
