### ISSUE TITLE
Research Arousal-Valence graphs

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#18]
Research Arousal-Valence graphs and how we can use them. Post research papers and thoughts here.

**Comment by TimvdLippe** [comment]
This ticket is for everyone, but @Azkle will summarize and cluster researched information.

**Comment by eanker** [comment]
To determine the valence we can use the tempo,loudness,timbre and pitch.
To determine the arousal we can use the mode, harmony and tonality.

Arousal and valence are unknown terms,so arousal means how calm or excited you are.
Valence on the other hand is the amount of attraction you have towards a certain event.

http://www2.ensc.sfu.ca/~ljilja/cnl/guests/Music.pdf
http://cisaweb.unige.ch/drupal/system/files/biblio/emo-11-4-921.pdf
