### ISSUE TITLE
Update requirements document

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#28]
Update the requirements document according to the product vision.

Fulfil all requirements of the guidelines posted on BlackBoard

**Comment by GijsWeterings** [comment]
Would like to discuss this with the product owner (@JeremybellEU), worst case on wednesday the 6th. We need to figure out prioritization of features.

**Comment by TimvdLippe** [comment]
We had a meeting today, were all questions answered?

**Comment by GijsWeterings** [comment]
The exact ordering is still somewhat variable. At this moment I have a draft ordering in [this](https://github.com/MoodCat/MoodCat.me/commit/f176ddc9793c2f008bb74a602a67e43b1175c304) commit.

**Comment by TimvdLippe** [comment]
This product is integrated in the product planning of #26. Leaving this ticket open as this is an external file included and should be treated as is.

**Comment by GijsWeterings** [comment]
waiting for #35
