### ISSUE TITLE
Design API call structure between frontend and backend

### ISSUE THREAD

**Issue by jwgmeligmeyling** [MoodCat/MoodCat.me#47]

**Comment by GijsWeterings** [comment]
RoomAPI
    - id
    - song [link]
    - time
    - name
    - users
    - msgs
    - position

```
@GET
/rooms

@GET
/rooms/{id}

@GET
/rooms/{id}/messages

@POST
/rooms/{id}/messages

@GET
/rooms/{id}/messages/{messageId}
```

SongAPI
    - id
    - streamURL
    - name
    - artist
    - artworkURL
    - duration
    - arousal
    - valence

```
@GET 
/songs

@GET
/songs/{id}

@POST
/songs/{id}/vote Param: roomid like/dislike

@POST
/songs/{id}/classify Param: valence arousal
```

**Comment by GijsWeterings** [comment]
/rooms/{id}/messages/{messageId}
has been found to be pretty useless, so we decided to skip it
