### ISSUE TITLE
Design VA voting system

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#57]
Design the neural network. Write this down for approval of teacher(-assistant).

**Comment by GijsWeterings** [comment]
http://www.multimediaeval.org/mediaeval2014/emotion2014/
http://freemusicarchive.org/
http://www.cs.waikato.ac.nz/ml/weka/
http://www.eecs.qmul.ac.uk/mmv/datasets/deap/doc/tac_special_issue_2011.pdf
http://www.salleurl.edu/tsenyal/true/imatgesTRUE/plugins/pluginSAM.jpg

**Comment by TimvdLippe** [comment]
SAMs are created on the frontend. 5 are placed next to each other for both arousal and valence. The  background could use a better styling, but positioning looks fine for now.
