### ISSUE TITLE
Create deployable version of the site

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#67]
To easily release a deployable version, we need to combine both frontend and backend into a single format in order to be run with 1 (or few) commands.

**Comment by TimvdLippe** [comment]
@GijsWeterings is the site at http://moodcat.me fully operational now?

**Comment by GijsWeterings** [comment]
@jaapp-- did the deployment in the end, so not sure

**Comment by GijsWeterings** [comment]
@jaapp-, that is

**Comment by jwgmeligmeyling** [comment]
It's operational but a sightly older version than we demo'd (containing the latest refactorings and bugfixes). Because we will implement song skipping really early in the sprint, I would suggest to redeploy after that fix.

**Comment by Jaapp-** [comment]
It's fully operational: the backend is just a clone of the github repo and mvn package can be run to update to newer versions. The frontend is a generated dist directory that has to be generated on another computer because the server has not enough RAM to use grunt to build the frontend.
